# Change these first
owner: MrTorfick # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Dash
    url: dash.starnode.us
  - name: Panel
    url: panel.starnode.us
  - name: Nodo 1
    url: usa1.starnode.us
  - name: Nodo 2
    url: usa2.starnode.us
  - name: Nodo 3
    url: usa3.starnode.us
  - name: Nodo 4:
    url: usa4.starnode.us 
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StarNode
  introTitle: "Estado **StarNode**"
  introMessage: Estado de los servicios de StarNode
  navbar:
    - title: Estado
      href: /
    - title: Discord
      href: https://discord.gg/gwFnTFXCSu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
